changelog:
  categories:
    - title: Solidus Core
      labels:
        - Solidus Core
    - title: Solidus Admin
      labels:
        - Solidus Admin
    - title: Solidus API
      labels:
        - Solidus API
