name: "Extract pipeline context"

on:
  workflow_call:
    inputs:
      last_minor:
        description: "Next release after this one is going to be a major?"
        type: boolean
        default: false

    outputs:
      current_tag:
        description: "Current tag"
        value: ${{ jobs.extract.outputs.current_tag }}
      candidate_tag:
        description: "Candidate tag"
        value: ${{ jobs.extract.outputs.candidate_tag }}
      candidate_version:
        description: "Candidate version"
        value: ${{ jobs.extract.outputs.candidate_version }}
      candidate_minor_version:
        description: "Candidate minor version"
        value: ${{ jobs.extract.outputs.candidate_minor_version }}
      candidate_patch_branch:
        description: "Candidate patch branch"
        value: ${{ jobs.extract.outputs.candidate_patch_branch }}
      next_candidate_tag:
        description: "Next candidate tag"
        value: ${{ jobs.extract.outputs.next_candidate_tag }}
      next_candidate_dev_version:
        description: "Next candidate dev version"
        value: ${{ jobs.extract.outputs.next_candidate_dev_version }}

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --tags origin
      - id: extraction
        name: "Extract context for the current pipeline"
        run: |
          cd dev_tools/ && bin/extract-pipeline-context \
            $GITHUB_OUTPUT \
            ${{ inputs.last_minor }} \
            ${{ github.ref_name }} \
            `git tag --list`
    outputs:
      current_tag: ${{ steps.extraction.outputs.current_tag }}
      candidate_tag: ${{ steps.extraction.outputs.candidate_tag }}
      candidate_version: ${{ steps.extraction.outputs.candidate_version }}
      candidate_minor_version: ${{ steps.extraction.outputs.candidate_minor_version }}
      candidate_patch_branch: ${{ steps.extraction.outputs.candidate_patch_branch }}
      next_candidate_tag: ${{ steps.extraction.outputs.next_candidate_tag }}
      next_candidate_dev_version: ${{ steps.extraction.outputs.next_candidate_dev_version }}
