name: "Prepare release"

on: workflow_dispatch

jobs:
  extract_pipeline_context:
    uses: "./.github/workflows/extract_pipeline_context.yml"

  prepare:
    runs-on: ubuntu-latest
    needs: extract_pipeline_context
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: "dev_tools/Gemfile"
        with:
          ruby-version: "3.1"
          bundler-cache: true
      - name: "Bump version"
        run: |
          cd dev_tools/ && bin/bump-version \
            ${{ needs.extract_pipeline_context.outputs.candidate_tag }}
      - name: "Bump docker image version"
        if: github.ref_name == 'master'
        run: |
          cd dev_tools/ && bin/bump-docker-image-version \
            ${{ needs.extract_pipeline_context.outputs.candidate_tag }}
      - name: "Update Changelog"
        run: |
          cd dev_tools/ && bin/update-changelog \
            ${{ github.token }} \
            ${{ github.repository }} \
            ${{ needs.extract_pipeline_context.outputs.candidate_tag }}
      - uses: ./.github/actions/commit_and_submit_pull_request
        with:
          labels: changelog:skip
          message: |
            Prepare release for Solidus ${{ needs.extract_pipeline_context.outputs.candidate_tag }}
            
            
            This code has been automatically generated by our 'Prepare release' GitHub
            action.

            The actual release is not part of the automation, and it still needs to be manually done by a maintainer.
